language: rust
sudo: required

rust:
  - stable
  - nightly
os: linux
matrix:
  fast_finish: true
services:
  - docker

cache: cargo

script:
  - cargo test --all
before_deploy:
  - ./ci/build-release.sh nobs ${TRAVIS_TAG}-${TRAVIS_OS_NAME}

notifications:
  email: false
deploy:
  - provider: releases
    api_key: $AUTH_TOKEN
    file:
      - "nobs-*"
    on:
      condition: $TRAVIS_RUST_VERSION = stable
      tags: true
    skip_cleanup: true
