[package]
name = "embed"
description = "Modified version of rust-embed"
version = "0.1.0"
authors = ["Michael Zhang <failed.down@gmail.com>", "pyros2097 <pyros2097@gmail.com>"]

[lib]
proc-macro = true

[dependencies]
syn = "0.11"
quote = "0.3"
lazy_static = "1.1"
walkdir = "2.2"
